### ISSUE TITLE
feat(dashboard): render monitoring form markdown

### ISSUE THREAD

**Issue by chrismclarke** [e-picsa/picsa-apps#302]
**Is your feature request related to a problem? Please describe.**
When uploading a form to kobocollect any markdown in the question is automatically converted to HTML in the final output. It would be nice if this could parsed within our system also

**Describe the solution you'd like**
Likely the best option would be to first convert the markdown to HTML within the backend docker API, so that when the output is received it is still just HTML. If not possible to get working it could be possibly to 

**Additional context**
There's a lot of packages that can handle markdown-html conversion. I can't remember if the API uses javascript or python, for JS there's a few listed at:
https://npmtrends.com/markdown-it-vs-marked-vs-remarkable-vs-showdown

I've used [marked](https://marked.js.org/) in the past and worked well but open to any. There are also likely multiple for python.

Example of form with markdown that does not render markdown in table headings:

https://dashboard.picsa.app/monitoring/79d4cc31-96bf-4ea6-b639-f7d09580a561
![image](https://github.com/user-attachments/assets/d3d39899-b674-4d6f-a034-9c5d285a12bb)

Original xlsx: 
[aABxJMaJqbqQjrCF6t9tkG.xlsx](https://github.com/user-attachments/files/16335624/aABxJMaJqbqQjrCF6t9tkG.xlsx)

**Comment by khalifan-kfan** [comment]
Hi @chrismclarke, Thanks for this issue and such a clear description,  I did some digging and the ```enketo-transformer```
library was already handling this issue, we had just disabled the feature, and I have pushed a fix for it on the docker API 
[PR](https://github.com/e-picsa/xlsx-to-enketo-converter/pull/1) , Please check this out and let me know if it's conclusive
